Fix panic in tracing due to invalid spans
We're getting the following panic:
thread 'tokio-runtime-worker' panicked at 'tried to drop a ref to Id(1),
but no such span exists!',
/home/geal/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-subscriber-0.2.25/src/registry/sharded.rs:346:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

This is probably caused by the root span getting dropped at the end of
the stream() method, while it is used by the returned stream. We must
make sure the span is valid for the entire life of the stream