Move sqlx query files to the apollo-router crate’s directory
At before this change, `.sqlx/query-*.json` is at workspace root
and therefore isn’t packaged with the `apollo-router` crate when making a release
which causes errors like

```
error: `SQLX_OFFLINE=true` but there is no cached data for this query
```

To reproduce:

```
cargo package -p apollo-router
```

The fix should be something like below,
but that seems to skip queries under `#[cfg(test)]` and remove corresponding files.
Meanwhile, this moves the files manually.

```
(cd apollo-router && DATABASE_URL=postgres://localhost cargo sqlx prepare)
```