Small CONTRIBUTING update to fix help command example
Without the additional `--` the router call returns:

```
error: Found argument 'help' which wasn't expected, or isn't valid in this context

USAGE:
    router [OPTIONS]

For more information try --help
```