Enough work to get the hyper branch to compile
Basically, replace BoxError in RouterBody with axum::Error.

It's definitely the right thing to do, so that's nice.

You can run a router now which will fail as soon as you make a request
because we aren't setting header timeouts correctly:

```
2024-12-05T12:37:54.067689Z INFO  Health check exposed at http://127.0.0.1:8088/health
2024-12-05T12:37:54.068947Z INFO  GraphQL endpoint exposed at http://127.0.0.1:4000/ 🚀
2024-12-05T12:37:54.899353Z ERROR  panicked at /Users/garypen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-1.5.1/src/common/time.rs:73:32:
timeout `header_read_timeout` set, but no timer set
```

We can continue this PM, I'm getting some lunch.