improve our rhai unit testing story (#2081)
Add unit tests for all rhai `request` and `response` accessors.

If a test fails, you'll see something like:

thread 'plugins::rhai::tests::it_can_process_supergraph_request'
panicked at 'test failed:
ErrorInFunctionCall("process_supergraph_request", "",
ErrorRuntime("query: expected: #{\"first\": 1}, actual: #{\"first\":
2}", 60:9), none)', apollo-router/src/plugins/rhai.rs:1749:16

Which is telling you why the rhai script failed (expected != actual) and
where it failed: functiona name, line number character offset. That
should be enough to figure out what the problem is.

also:
 - add support for reading the query_plan from an ExecutionRequest
 - add contains function for context